CREATE TABLE IF NOT EXISTS PRODUCT
(
    PRODUCT_ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(100),
    PRICE BIGINT,
);

CREATE TABLE IF NOT EXISTS DISCOUNT
(
    PRODUCT INTEGER,
    QUANTITY BIGINT,
    PRICE BIGINT,
);
