INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (1, 'Rolex', 10000);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (2, 'Michael Kors', 8000);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (3, 'Swatch', 5000);
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (4, 'Casio', 3000);