INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (1, 'Rolex', '100');
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (2, 'Michael Kors', '80');
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (3, 'Swatch', '50');
INSERT INTO PRODUCT (PRODUCT_ID, NAME, PRICE) VALUES (4, 'Casio', '30');